apiVersion: v1
kind: PersistentVolume
metadata:
  name: cart-trans-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/charters/temp/demo-trans-storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cart-trans-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi